### ISSUE TITLE
about casting json strings output to number 

### ISSUE THREAD

**Issue by vjeantet** [palmerabollo/grok#2]
Did you have a look to jq ?
it's a powerfull tool to manipulate json from command line.

it can change string to number from a json input, and even "reword" a json input "schema" to another one..

http://stedolan.github.io/jq/tutorial/

**Comment by palmerabollo** [comment]
@vjeantet Yes, that is an option. However, I think it is better to include it as part of "grok", because type conversion (to int and float) is part of the grok "standard" if I'm not wrong.

I'm currently working on a new function (called `ParseType`) [on a branch](https://github.com/palmerabollo/grok/tree/feature/ParseType) as we [discussed here](https://github.com/gemsi/grok/issues/10). I'll send a PR next week once I clean the code.

You can [see the changes here](https://github.com/gemsi/grok/compare/master...palmerabollo:feature/ParseType?expand=1), any comments are welcome.
